const fs = require('fs');

const surveyTranslationsHi = {
  "Electrical Work": "बिजली कार्य",
  "Plumbing": "प्लंबिंग",
  "Carpentry": "बढ़ईगिरी",
  "Cleaning": "सफाई",
  "Painting": "पेंटिंग",
  "Appliance Repair": "उपकरण मरम्मत",
  "Mason / Construction": "राजमिस्त्री / निर्माण",
  "Other": "अन्य",
  "Electrical Wiring": "विद्युत वायरिंग",
  "Switch / Board Repair": "स्विच / बोर्ड मरम्मत",
  "Pipe Fitting": "पाइप फिटिंग",
  "Leakage Repair": "रिसाव की मरम्मत",
  "Furniture Making": "फर्नीचर बनाना",
  "Cabinet Work": "कैबिनेट का काम",
  "Tile Work": "टाइल का काम",
  "Deep Cleaning": "डीप क्लीनिंग",
  "Bathroom Cleaning": "बाथरूम की सफाई",
  "Wall Painting": "दीवार पेंटिंग",
  "Spray Painting": "स्प्रे पेंटिंग",
  "Appliance Installation": "उपकरण स्थापना",
  "General Repair Work": "सामान्य मरम्मत कार्य",
  "Less than 6 months": "6 महीने से कम",
  "6 months – 1 year": "6 महीने - 1 साल",
  "1 – 3 years": "1 - 3 साल",
  "3 – 5 years": "3 - 5 साल",
  "5 – 10 years": "5 - 10 साल",
  "10+ years": "10+ साल",
  "Self-employed": "स्वरोजगार",
  "Worked under contractor": "ठेकेदार के अधीन काम किया",
  "Worked in company": "कंपनी में काम किया",
  "Mix of all": "सभी का मिश्रण",
  "0 – 10": "0 - 10",
  "10 – 50": "10 - 50",
  "50 – 200": "50 - 200",
  "200+": "200+",
  "No tools": "कोई उपकरण नहीं",
  "Basic tools": "बुनियादी उपकरण",
  "Most required tools": "अधिकतर आवश्यक उपकरण",
  "Complete professional tools": "पूर्ण पेशेवर उपकरण",
  "Client provides everything": "ग्राहक सब कुछ प्रदान करता है",
  "I can suggest materials": "मैं सामग्री सुझा सकता हूँ",
  "I can arrange materials": "मैं सामग्री की व्यवस्था कर सकता हूँ",
  "Full-time": "पूर्णकालिक",
  "Part-time": "अंशकालिक",
  "Only weekend": "केवल सप्ताहांत",
  "Morning": "सुबह",
  "Afternoon": "दोपहर",
  "Evening": "शाम",
  "Flexible": "लचीला",
  "Small quick jobs": "छोटे त्वरित काम",
  "Long-duration work": "लंबे समय के काम",
  "Urgent jobs": "तत्काल काम",
  "Regular work": "नियमित काम",
  "Within 2 km": "2 किमी के भीतर",
  "Within 5 km": "5 किमी के भीतर",
  "Within 10 km": "10 किमी के भीतर",
  "Anywhere in city": "शहर में कहीं भी",
  "Only nearby": "केवल आस-पास",
  "Within city": "शहर के भीतर",
  "Outside city": "शहर के बाहर",
  "Yes": "हाँ",
  "No": "नहीं",
  "Hindi": "हिंदी",
  "English": "अंग्रेज़ी",
  "Punjabi": "पंजाबी",
  "Per hour": "प्रति घंटा",
  "Per job": "प्रति कार्य",
  "₹300 – ₹500": "₹300 – ₹500",
  "₹500 – ₹800": "₹500 – ₹800",
  "₹800 – ₹1200": "₹800 – ₹1200",
  "₹1200+": "₹1200+",
  "Aadhaar Card": "आधार कार्ड",
  "Driving License": "ड्राइविंग लाइसेंस",
  "Voter ID": "वोटर आईडी",
  "Always": "हमेशा",
  "Most of the time": "ज्यादातर समय",
  "Depends on situation": "स्थिति पर निर्भर करता है",
  "Never": "कभी नहीं",
  "Rarely": "शायद ही कभी",
  "Sometimes": "कभी-कभी",
  "What is your main skill?": "आपका मुख्य कौशल क्या है?",
  "What other work can you do?": "आप और क्या काम कर सकते हैं?",
  "Tell us about your experience": "हमें अपने अनुभव के बारे में बताएं",
  "Tools & Capability": "उपकरण और क्षमता",
  "Availability & Work Preference": "उपलब्धता और कार्य प्राथमिकता",
  "Travel & Mobility": "यात्रा और गतिशीलता",
  "Communication": "संचार",
  "Pricing": "मूल्य निर्धारण",
  "Trust & Verification": "विश्वास और सत्यापन",
  "Reliability": "विश्वसनीयता",
  "Select your primary skill area": "अपना प्राथमिक कौशल क्षेत्र चुनें",
  "Select all additional skills you have": "आपके पास मौजूद सभी अतिरिक्त कौशल चुनें",
  "Help us understand your work history": "हमें आपका कार्य इतिहास समझने में मदद करें",
  "What tools and materials can you handle?": "आप किन उपकरणों और सामग्रियों को संभाल सकते हैं?",
  "When and how do you prefer to work?": "आप कब और कैसे काम करना पसंद करते हैं?",
  "How far can you travel for work?": "काम के लिए आप कितनी दूर यात्रा कर सकते हैं?",
  "Which languages do you speak?": "आप कौन सी भाषाएं बोलते हैं?",
  "How do you want to get paid?": "आप भुगतान कैसे प्राप्त करना चाहते हैं?",
  "Upload documents for verification": "सत्यापन के लिए दस्तावेज़ अपलोड करें",
  "Tell us about your work commitment": "हमें अपनी कार्य प्रतिबद्धता के बारे में बताएं",
  "How much experience do you have?": "आपके पास कितना अनुभव है?",
  "Where have you worked before?": "आपने पहले कहाँ काम किया है?",
  "Approximately how many jobs have you completed?": "आपने लगभग कितने कार्य पूरे किए हैं?",
  "Do you have your own tools?": "क्या आपके पास अपने उपकरण हैं?",
  "Who will provide materials?": "सामग्री कौन प्रदान करेगा?",
  "How do you want to work?": "आप कैसे काम करना चाहते हैं?",
  "When are you usually available?": "आप आमतौर पर कब उपलब्ध होते हैं?",
  "What type of jobs do you prefer? (Select all that apply)": "आप किस प्रकार के कार्य पसंद करते हैं? (सभी लागू चुनें)",
  "How far can you travel?": "आप कितनी दूर यात्रा कर सकते हैं?",
  "Are you willing to travel far if needed?": "क्या आप जरूरत पड़ने पर दूर यात्रा करने के इच्छुक हैं?",
  "Do you have your own vehicle?": "क्या आपके पास अपना वाहन है?",
  "Which languages can you speak? (Select all that apply)": "आप कौन सी भाषाएँ बोल सकते हैं? (सभी लागू चुनें)",
  "How do you prefer to get paid?": "आप कैसे भुगतान प्राप्त करना पसंद करते हैं?",
  "What is your expected minimum earning per day?": "प्रति दिन आपकी अपेक्षित न्यूनतम कमाई क्या है?",
  "Upload your ID proof": "अपना आईडी प्रूफ अपलोड करें",
  "Do you have photos of your past work?": "क्या आपके पास अपने पिछले काम की तस्वीरें हैं?",
  "Upload Work Photos": "काम की तस्वीरें अपलोड करें",
  "Do you have any certification?": "क्या आपके पास कोई प्रमाण पत्र है?",
  "If you accept a job, will you complete it on time?": "यदि आप कोई काम स्वीकार करते हैं, तो क्या आप उसे समय पर पूरा करेंगे?",
  "How often do you cancel jobs?": "आप कितनी बार नौकरियां रद्द करते हैं?",
  "Complete Profile": "प्रोफ़ाइल पूरी करें",
  "Continue": "जारी रखें",
  "Upload": "अपलोड",
  "I want stable and regular work": "मुझे स्थिर और नियमित काम चाहिए",
  "I want higher earning opportunities": "मुझे अधिक कमाई के अवसर चाहिए",
  "I want to grow professionally": "मैं पेशेवर रूप से विकसित होना चाहता हूँ",
  "Just exploring": "बस खोज रहा हूँ",
  "Less than 1 year": "1 साल से कम",
  "Less than 20": "20 से कम",
  "Small basic jobs": "छोटे बुनियादी काम",
  "Mixed work": "मिश्रित काम",
  "Complex / professional jobs": "जटिल / पेशेवर काम",
  "General work": "सामान्य काम",
  "Skilled work": "कुशल काम",
  "Advanced / expert work": "उन्नत / विशेषज्ञ काम",
  "Yes, independently": "हाँ, स्वतंत्र रूप से",
  "Yes, with some help": "हाँ, कुछ मदद के साथ",
  "Complete professional setup": "पूर्ण पेशेवर सेटअप",
  "Alone": "अकेले",
  "With helper": "सहायक के साथ",
  "Small team": "छोटी टीम",
  "Yes, always": "हाँ हमेशा",
  "Mostly": "अधिकतर",
  "Depends": "निर्भर करता है",
  "2–4 hours": "2-4 घंटे",
  "4–8 hours": "4-8 घंटे",
  "8+ hours": "8+ घंटे",
  "Yes, I will upload": "हाँ, मैं अपलोड करूँगा",
  "Why do you want to become a WorkLink Employee?": "आप WorkLink कर्मचारी क्यों बनना चाहते हैं?",
  "Experience Qualification": "अनुभव योग्यता",
  "Skill Depth": "कौशल की गहराई",
  "Tools & Professional Setup": "उपकरण और पेशेवर सेटअप",
  "Reliability & Discipline": "विश्वसनीयता और अनुशासन",
  "Platform Rules Acceptance": "मंच नियम स्वीकृति",
  "Verification Readiness": "सत्यापन तत्परता",
  "Availability Commitment": "उपलब्धता प्रतिबद्धता",
  "Proof of Work": "काम का प्रमाण",
  "Select your main motivation": "अपनी मुख्य प्रेरणा चुनें",
  "We want to understand your skill level": "हम आपके कौशल स्तर को समझना चाहते हैं",
  "Your professional equipment and work style": "आपका पेशेवर उपकरण और कार्य शैली",
  "This is the most important section": "यह सबसे महत्वपूर्ण खंड है",
  "Agree to WorkLink platform policies": "WorkLink मंच नीतियों से सहमत हों",
  "Confirm you are ready for verification": "पुष्टि करें कि आप सत्यापन के लिए तैयार हैं",
  "How much time can you dedicate?": "आप कितना समय दे सकते हैं?",
  "Show us your work quality": "हमें अपने काम की गुणवत्ता दिखाएं",
  "How much experience do you have in your main skill?": "आपके मुख्य कौशल में आपको कितना अनुभव है?",
  "How many jobs have you completed?": "आपने कितने कार्य पूरे किए हैं?",
  "What type of work have you mostly done?": "आपने अधिकतर किस प्रकार का कार्य किया है?",
  "What is your specialization?": "आपकी विशेषज्ञता क्या है?",
  "Can you handle complex or unexpected problems on-site?": "क्या आप साइट पर जटिल या अप्रत्याशित समस्याओं को संभाल सकते हैं?",
  "What tools do you have?": "आपके पास क्या उपकरण हैं?",
  "Do you work alone or with a team?": "क्या आप अकेले काम करते हैं या टीम के साथ?",
  "How often do you reach job location on time?": "आप काम के स्थान पर कितनी बार समय पर पहुँचते हैं?",
  "Are you willing to accept auto-assigned jobs from WorkLink?": "क्या आप WorkLink से स्वतः-असाइन की गई नौकरियों को स्वीकार करने के लिए तैयार हैं?",
  "Are you okay with platform commission on each job?": "क्या आप प्रत्येक कार्य पर मंच कमीशन के साथ ठीक हैं?",
  "Will you follow WorkLink service standards and behavior rules?": "क्या आप WorkLink सेवा मानकों और व्यवहार नियमों का पालन करेंगे?",
  "Are you ready for full verification (ID & background check)?": "क्या आप पूर्ण सत्यापन (आईडी और पृष्ठभूमि की जांच) के लिए तैयार हैं?",
  "Are you ready for offline skill testing?": "क्या आप ऑफ़लाइन कौशल परीक्षण के लिए तैयार हैं?",
  "Are you open to training before activation (if required)?": "क्या आप सक्रियण से पहले प्रशिक्षण के लिए खुले हैं (यदि आवश्यक हो)?",
  "How will you work with WorkLink?": "आप WorkLink के साथ कैसे काम करेंगे?",
  "How many hours can you work daily?": "आप रोजाना कितने घंटे काम कर सकते हैं?",
  "Upload photos of your past work (required)": "अपने पिछले काम की तस्वीरें अपलोड करें (आवश्यक)",
  "Can you provide a previous client reference?": "क्या आप पिछले ग्राहक का संदर्भ प्रदान कर सकते हैं?",
  "Submit Application": "आवेदन जमा करें",
  "Priority Matches": "प्राथमिकता मिलान",
  "Workforce Development": "कार्यबल विकास",
  "Looking for matches...": "मिलान खोज रहा हूँ...",
  "Priority assignments will appear here": "प्राथमिकता कार्य यहाँ दिखाई देंगे",
};

const surveyTranslationsPa = {
  "Electrical Work": "ਇਲੈਕਟ੍ਰੀਕਲ ਕੰਮ",
  "Plumbing": "ਪਲੰਬਿੰਗ",
  "Carpentry": "ਤਰਖਾਣ ਦਾ ਕੰਮ",
  "Cleaning": "ਸਫਾਈ",
  "Painting": "ਪੇਂਟਿੰਗ",
  "Appliance Repair": "ਉਪਕਰਨ ਦੀ ਮੁਰੰਮਤ",
  "Mason / Construction": "ਮਿਸਤਰੀ / ਉਸਾਰੀ",
  "Other": "ਹੋਰ",
  "Electrical Wiring": "ਬਿਜਲੀ ਦੀਆਂ ਤਾਰਾਂ",
  "Switch / Board Repair": "ਸਵਿੱਚ / ਬੋਰਡ ਦੀ ਮੁਰੰਮਤ",
  "Pipe Fitting": "ਪਾਈਪ ਫਿਟਿੰਗ",
  "Leakage Repair": "ਲੀਕੇਜ ਦੀ ਮੁਰੰਮਤ",
  "Furniture Making": "ਫਰਨੀਚਰ ਬਣਾਉਣਾ",
  "Cabinet Work": "ਕੈਬਿਨੇਟ ਦਾ ਕੰਮ",
  "Tile Work": "ਟਾਈਲ ਦਾ ਕੰਮ",
  "Deep Cleaning": "ਡੂੰਘੀ ਸਫਾਈ",
  "Bathroom Cleaning": "ਬਾਥਰੂਮ ਦੀ ਸਫਾਈ",
  "Wall Painting": "ਕੰਧ ਪੇਂਟਿੰਗ",
  "Spray Painting": "ਸਪਰੇਅ ਪੇਂਟਿੰਗ",
  "Appliance Installation": "ਉਪਕਰਨ ਸਥਾਪਨਾ",
  "General Repair Work": "ਆਮ ਮੁਰੰਮਤ ਦਾ ਕੰਮ",
  "Less than 6 months": "6 ਮਹੀਨਿਆਂ ਤੋਂ ਘੱਟ",
  "6 months – 1 year": "6 ਮਹੀਨੇ - 1 ਸਾਲ",
  "1 – 3 years": "1 - 3 ਸਾਲ",
  "3 – 5 years": "3 - 5 ਸਾਲ",
  "5 – 10 years": "5 - 10 ਸਾਲ",
  "10+ years": "10+ ਸਾਲ",
  "Self-employed": "ਸਵੈ-ਰੁਜ਼ਗਾਰ",
  "Worked under contractor": "ਠੇਕੇਦਾਰ ਅਧੀਨ ਕੰਮ ਕੀਤਾ",
  "Worked in company": "ਕੰਪਨੀ ਵਿੱਚ ਕੰਮ ਕੀਤਾ",
  "Mix of all": "ਸਾਰਿਆਂ ਦਾ ਮਿਸ਼ਰਣ",
  "0 – 10": "0 - 10",
  "10 – 50": "10 - 50",
  "50 – 200": "50 - 200",
  "200+": "200+",
  "No tools": "ਕੋਈ ਸੰਦ ਨਹੀਂ",
  "Basic tools": "ਬੁਨਿਆਦੀ ਸੰਦ",
  "Most required tools": "ਜ਼ਿਆਦਾਤਰ ਲੋੜੀਂਦੇ ਸੰਦ",
  "Complete professional tools": "ਸੰਪੂਰਨ ਪੇਸ਼ੇਵਰ ਸੰਦ",
  "Client provides everything": "ਗਾਹਕ ਸਭ ਕੁਝ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ",
  "I can suggest materials": "ਮੈਂ ਸਮੱਗਰੀ ਦਾ ਸੁਝਾਅ ਦੇ ਸਕਦਾ ਹਾਂ",
  "I can arrange materials": "ਮੈਂ ਸਮੱਗਰੀ ਦਾ ਪ੍ਰਬੰਧ ਕਰ ਸਕਦਾ ਹਾਂ",
  "Full-time": "ਪੂਰਾ ਸਮਾਂ",
  "Part-time": "ਪਾਰਟ-ਟਾਈਮ",
  "Only weekend": "ਸਿਰਫ ਵੀਕਐਂਡ",
  "Morning": "ਸਵੇਰ",
  "Afternoon": "ਦੁਪਹਿਰ",
  "Evening": "ਸ਼ਾਮ",
  "Flexible": "ਲਚਕਦਾਰ",
  "Small quick jobs": "ਛੋਟੇ ਤੇਜ਼ ਕੰਮ",
  "Long-duration work": "ਲੰਬੇ ਸਮੇਂ ਦਾ ਕੰਮ",
  "Urgent jobs": "ਜ਼ਰੂਰੀ ਕੰਮ",
  "Regular work": "ਨਿਯਮਤ ਕੰਮ",
  "Within 2 km": "2 ਕਿਲੋਮੀਟਰ ਦੇ ਅੰਦਰ",
  "Within 5 km": "5 ਕਿਲੋਮੀਟਰ ਦੇ ਅੰਦਰ",
  "Within 10 km": "10 ਕਿਲੋਮੀਟਰ ਦੇ ਅੰਦਰ",
  "Anywhere in city": "ਸ਼ਹਿਰ ਵਿੱਚ ਕਿਤੇ ਵੀ",
  "Only nearby": "ਸਿਰਫ ਨੇੜੇ",
  "Within city": "ਸ਼ਹਿਰ ਦੇ ਅੰਦਰ",
  "Outside city": "ਸ਼ਹਿਰ ਦੇ ਬਾਹਰ",
  "Yes": "ਹਾਂ",
  "No": "ਨਹੀਂ",
  "Hindi": "ਹਿੰਦੀ",
  "English": "ਅੰਗਰੇਜ਼ੀ",
  "Punjabi": "ਪੰਜਾਬੀ",
  "Per hour": "ਪ੍ਰਤੀ ਘੰਟਾ",
  "Per job": "ਪ੍ਰਤੀ ਕੰਮ",
  "₹300 – ₹500": "₹300 – ₹500",
  "₹500 – ₹800": "₹500 – ₹800",
  "₹800 – ₹1200": "₹800 – ₹1200",
  "₹1200+": "₹1200+",
  "Aadhaar Card": "ਆਧਾਰ ਕਾਰਡ",
  "Driving License": "ਡਰਾਈਵਿੰਗ ਲਾਇਸੈਂਸ",
  "Voter ID": "ਵੋਟਰ ਆਈ.ਡੀ",
  "Always": "ਹਮੇਸ਼ਾ",
  "Most of the time": "ਜ਼ਿਆਦਾਤਰ ਸਮਾਂ",
  "Depends on situation": "ਸਥਿਤੀ 'ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ",
  "Never": "ਕਦੇ ਨਹੀਂ",
  "Rarely": "ਬਹੁਤ ਘੱਟ",
  "Sometimes": "ਕਦੇ-ਕਦੇ",
  "What is your main skill?": "ਤੁਹਾਡਾ ਮੁੱਖ ਹੁਨਰ ਕੀ ਹੈ?",
  "What other work can you do?": "ਤੁਸੀਂ ਹੋਰ ਕੀ ਕੰਮ ਕਰ ਸਕਦੇ ਹੋ?",
  "Tell us about your experience": "ਸਾਨੂੰ ਆਪਣੇ ਤਜ਼ਰਬੇ ਬਾਰੇ ਦੱਸੋ",
  "Tools & Capability": "ਸੰਦ ਅਤੇ ਸਮਰੱਥਾ",
  "Availability & Work Preference": "ਉਪਲਬਧਤਾ ਅਤੇ ਕੰਮ ਦੀ ਤਰਜੀਹ",
  "Travel & Mobility": "ਯਾਤਰਾ ਅਤੇ ਗਤੀਸ਼ੀਲਤਾ",
  "Communication": "ਸੰਚਾਰ",
  "Pricing": "ਕੀਮਤ",
  "Trust & Verification": "ਭਰੋਸਾ ਅਤੇ ਤਸਦੀਕ",
  "Reliability": "ਭਰੋਸੇਯੋਗਤਾ",
  "Select your primary skill area": "ਆਪਣਾ ਪ੍ਰਾਇਮਰੀ ਹੁਨਰ ਖੇਤਰ ਚੁਣੋ",
  "Select all additional skills you have": "ਤੁਹਾਡੇ ਕੋਲ ਮੌਜੂਦ ਸਾਰੇ ਵਾਧੂ ਹੁਨਰ ਚੁਣੋ",
  "Help us understand your work history": "ਤੁਹਾਡੇ ਕੰਮ ਦੇ ਇਤਿਹਾਸ ਨੂੰ ਸਮਝਣ ਵਿੱਚ ਸਾਡੀ ਮਦਦ ਕਰੋ",
  "What tools and materials can you handle?": "ਤੁਸੀਂ ਕਿਹੜੇ ਸੰਦ ਅਤੇ ਸਮੱਗਰੀ ਨੂੰ ਸੰਭਾਲ ਸਕਦੇ ਹੋ?",
  "When and how do you prefer to work?": "ਤੁਸੀਂ ਕਦੋਂ ਅਤੇ ਕਿਵੇਂ ਕੰਮ ਕਰਨਾ ਪਸੰਦ ਕਰਦੇ ਹੋ?",
  "How far can you travel for work?": "ਕੰਮ ਲਈ ਤੁਸੀਂ ਕਿੰਨੀ ਦੂਰ ਸਫ਼ਰ ਕਰ ਸਕਦੇ ਹੋ?",
  "Which languages do you speak?": "ਤੁਸੀਂ ਕਿਹੜੀਆਂ ਭਾਸ਼ਾਵਾਂ ਬੋਲਦੇ ਹੋ?",
  "How do you want to get paid?": "ਤੁਸੀਂ ਭੁਗਤਾਨ ਕਿਵੇਂ ਪ੍ਰਾਪਤ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
  "Upload documents for verification": "ਤਸਦੀਕ ਲਈ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
  "Tell us about your work commitment": "ਸਾਨੂੰ ਆਪਣੀ ਕੰਮ ਪ੍ਰਤੀਬੱਧਤਾ ਬਾਰੇ ਦੱਸੋ",
  "How much experience do you have?": "ਤੁਹਾਡੇ ਕੋਲ ਕਿੰਨਾ ਤਜਰਬਾ ਹੈ?",
  "Where have you worked before?": "ਤੁਸੀਂ ਪਹਿਲਾਂ ਕਿੱਥੇ ਕੰਮ ਕੀਤਾ ਹੈ?",
  "Approximately how many jobs have you completed?": "ਤੁਸੀਂ ਲਗਭਗ ਕਿੰਨੇ ਕੰਮ ਪੂਰੇ ਕੀਤੇ ਹਨ?",
  "Do you have your own tools?": "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਆਪਣੇ ਸੰਦ ਹਨ?",
  "Who will provide materials?": "ਸਮੱਗਰੀ ਕੌਣ ਪ੍ਰਦਾਨ ਕਰੇਗਾ?",
  "How do you want to work?": "ਤੁਸੀਂ ਕਿਵੇਂ ਕੰਮ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
  "When are you usually available?": "ਤੁਸੀਂ ਆਮ ਤੌਰ 'ਤੇ ਕਦੋਂ ਉਪਲਬਧ ਹੁੰਦੇ ਹੋ?",
  "What type of jobs do you prefer? (Select all that apply)": "ਤੁਸੀਂ ਕਿਸ ਕਿਸਮ ਦੀਆਂ ਨੌਕਰੀਆਂ ਨੂੰ ਤਰਜੀਹ ਦਿੰਦੇ ਹੋ? (ਸਾਰੇ ਲਾਗੂ ਚੁਣੋ)",
  "How far can you travel?": "ਤੁਸੀਂ ਕਿੰਨੀ ਦੂਰ ਯਾਤਰਾ ਕਰ ਸਕਦੇ ਹੋ?",
  "Are you willing to travel far if needed?": "ਕੀ ਤੁਸੀਂ ਲੋੜ ਪੈਣ 'ਤੇ ਦੂਰ ਸਫ਼ਰ ਕਰਨ ਲਈ ਤਿਆਰ ਹੋ?",
  "Do you have your own vehicle?": "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਆਪਣਾ ਵਾਹਨ ਹੈ?",
  "Which languages can you speak? (Select all that apply)": "ਤੁਸੀਂ ਕਿਹੜੀਆਂ ਭਾਸ਼ਾਵਾਂ ਬੋਲ ਸਕਦੇ ਹੋ? (ਸਾਰੇ ਲਾਗੂ ਚੁਣੋ)",
  "How do you prefer to get paid?": "ਤੁਸੀਂ ਭੁਗਤਾਨ ਕਿਵੇਂ ਪ੍ਰਾਪਤ ਕਰਨਾ ਪਸੰਦ ਕਰਦੇ ਹੋ?",
  "What is your expected minimum earning per day?": "ਪ੍ਰਤੀ ਦਿਨ ਤੁਹਾਡੀ ਉਮੀਦ ਕੀਤੀ ਘੱਟੋ ਘੱਟ ਕਮਾਈ ਕੀ ਹੈ?",
  "Upload your ID proof": "ਆਪਣਾ ਆਈ.ਡੀ. ਪ੍ਰੂਫ ਅਪਲੋਡ ਕਰੋ",
  "Do you have photos of your past work?": "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਆਪਣੇ ਪਿਛਲੇ ਕੰਮ ਦੀਆਂ ਫੋਟੋਆਂ ਹਨ?",
  "Upload Work Photos": "ਕੰਮ ਦੀਆਂ ਫੋਟੋਆਂ ਅੱਪਲੋਡ ਕਰੋ",
  "Do you have any certification?": "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਕੋਈ ਪ੍ਰਮਾਣ ਪੱਤਰ ਹੈ?",
  "If you accept a job, will you complete it on time?": "ਜੇ ਤੁਸੀਂ ਕੋਈ ਨੌਕਰੀ ਸਵੀਕਾਰ ਕਰਦੇ ਹੋ, ਤਾਂ ਕੀ ਤੁਸੀਂ ਇਸਨੂੰ ਸਮੇਂ ਸਿਰ ਪੂਰਾ ਕਰੋਗੇ?",
  "How often do you cancel jobs?": "ਤੁਸੀਂ ਕਿੰਨੀ ਵਾਰ ਨੌਕਰੀਆਂ ਰੱਦ ਕਰਦੇ ਹੋ?",
  "Complete Profile": "ਪ੍ਰੋਫਾਈਲ ਪੂਰਾ ਕਰੋ",
  "Continue": "ਜਾਰੀ ਰੱਖੋ",
  "Upload": "ਅੱਪਲੋਡ ਕਰੋ",
  "I want stable and regular work": "ਮੈਨੂੰ ਸਥਿਰ ਅਤੇ ਨਿਯਮਤ ਕੰਮ ਚਾਹੀਦਾ ਹੈ",
  "I want higher earning opportunities": "ਮੈਂ ਉੱਚ ਕਮਾਈ ਦੇ ਮੌਕੇ ਚਾਹੁੰਦਾ ਹਾਂ",
  "I want to grow professionally": "ਮੈਂ ਪੇਸ਼ੇਵਰ ਤੌਰ 'ਤੇ ਵਧਣਾ ਚਾਹੁੰਦਾ ਹਾਂ",
  "Just exploring": "ਸਿਰਫ਼ ਖੋਜ ਕਰ ਰਿਹਾ ਹਾਂ",
  "Less than 1 year": "1 ਸਾਲ ਤੋਂ ਘੱਟ",
  "Less than 20": "20 ਤੋਂ ਘੱਟ",
  "Small basic jobs": "ਛੋਟੇ ਬੁਨਿਆਦੀ ਕੰਮ",
  "Mixed work": "ਮਿਸ਼ਰਤ ਕੰਮ",
  "Complex / professional jobs": "ਗੁੰਝਲਦਾਰ / ਪੇਸ਼ੇਵਰ ਨੌਕਰੀਆਂ",
  "General work": "ਆਮ ਕੰਮ",
  "Skilled work": "ਹੁਨਰਮੰਦ ਕੰਮ",
  "Advanced / expert work": "ਉੱਨਤ / ਮਾਹਰ ਕੰਮ",
  "Yes, independently": "ਹਾਂ, ਸੁਤੰਤਰ ਤੌਰ 'ਤੇ",
  "Yes, with some help": "ਹਾਂ, ਕੁਝ ਮਦਦ ਨਾਲ",
  "Complete professional setup": "ਸੰਪੂਰਨ ਪੇਸ਼ੇਵਰ ਸੈੱਟਅੱਪ",
  "Alone": "ਇਕੱਲੇ",
  "With helper": "ਸਹਾਇਕ ਨਾਲ",
  "Small team": "ਛੋਟੀ ਟੀਮ",
  "Yes, always": "ਹਾਂ ਹਮੇਸ਼ਾ",
  "Mostly": "ਜਿਆਦਾਤਰ",
  "Depends": "ਨਿਰਭਰ ਕਰਦਾ ਹੈ",
  "2–4 hours": "2-4 ਘੰਟੇ",
  "4–8 hours": "4-8 ਘੰਟੇ",
  "8+ hours": "8+ ਘੰਟੇ",
  "Yes, I will upload": "ਹਾਂ, ਮੈਂ ਅਪਲੋਡ ਕਰਾਂਗਾ",
  "Why do you want to become a WorkLink Employee?": "ਤੁਸੀਂ WorkLink ਕਰਮਚਾਰੀ ਕਿਉਂ ਬਣਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
  "Experience Qualification": "ਅਨੁਭਵ ਯੋਗਤਾ",
  "Skill Depth": "ਹੁਨਰ ਦੀ ਡੂੰਘਾਈ",
  "Tools & Professional Setup": "ਸੰਦ ਅਤੇ ਪੇਸ਼ੇਵਰ ਸੈੱਟਅੱਪ",
  "Reliability & Discipline": "ਭਰੋਸੇਯੋਗਤਾ ਅਤੇ ਅਨੁਸ਼ਾਸਨ",
  "Platform Rules Acceptance": "ਪਲੇਟਫਾਰਮ ਨਿਯਮਾਂ ਦੀ ਸਵੀਕ੍ਰਿਤੀ",
  "Verification Readiness": "ਤਸਦੀਕ ਤਿਆਰੀ",
  "Availability Commitment": "ਉਪਲਬਧਤਾ ਪ੍ਰਤੀਬੱਧਤਾ",
  "Proof of Work": "ਕੰਮ ਦਾ ਸਬੂਤ",
  "Select your main motivation": "ਆਪਣੀ ਮੁੱਖ ਪ੍ਰੇਰਣਾ ਚੁਣੋ",
  "We want to understand your skill level": "ਅਸੀਂ ਤੁਹਾਡੇ ਹੁਨਰ ਦੇ ਪੱਧਰ ਨੂੰ ਸਮਝਣਾ ਚਾਹੁੰਦੇ ਹਾਂ",
  "Your professional equipment and work style": "ਤੁਹਾਡੇ ਪੇਸ਼ੇਵਰ ਉਪਕਰਣ ਅਤੇ ਕੰਮ ਦੀ ਸ਼ੈਲੀ",
  "This is the most important section": "ਇਹ ਸਭ ਤੋਂ ਮਹੱਤਵਪੂਰਨ ਭਾਗ ਹੈ",
  "Agree to WorkLink platform policies": "WorkLink ਪਲੇਟਫਾਰਮ ਨੀਤੀਆਂ ਨਾਲ ਸਹਿਮਤ ਹੋਵੋ",
  "Confirm you are ready for verification": "ਪੁਸ਼ਟੀ ਕਰੋ ਕਿ ਤੁਸੀਂ ਤਸਦੀਕ ਲਈ ਤਿਆਰ ਹੋ",
  "How much time can you dedicate?": "ਤੁਸੀਂ ਕਿੰਨਾ ਸਮਾਂ ਦੇ ਸਕਦੇ ਹੋ?",
  "Show us your work quality": "ਸਾਨੂੰ ਆਪਣੇ ਕੰਮ ਦੀ ਗੁਣਵੱਤਾ ਦਿਖਾਓ",
  "How much experience do you have in your main skill?": "ਤੁਹਾਡੇ ਮੁੱਖ ਹੁਨਰ ਵਿੱਚ ਤੁਹਾਡੇ ਕੋਲ ਕਿੰਨਾ ਤਜਰਬਾ ਹੈ?",
  "How many jobs have you completed?": "ਤੁਸੀਂ ਕਿੰਨੇ ਕੰਮ ਪੂਰੇ ਕੀਤੇ ਹਨ?",
  "What type of work have you mostly done?": "ਤੁਸੀਂ ਜ਼ਿਆਦਾਤਰ ਕਿਸ ਕਿਸਮ ਦਾ ਕੰਮ ਕੀਤਾ ਹੈ?",
  "What is your specialization?": "ਤੁਹਾਡੀ ਮੁਹਾਰਤ ਕੀ ਹੈ?",
  "Can you handle complex or unexpected problems on-site?": "ਕੀ ਤੁਸੀਂ ਸਾਈਟ 'ਤੇ ਗੁੰਝਲਦਾਰ ਜਾਂ ਅਚਾਨਕ ਸਮੱਸਿਆਵਾਂ ਨੂੰ ਸੰਭਾਲ ਸਕਦੇ ਹੋ?",
  "What tools do you have?": "ਤੁਹਾਡੇ ਕੋਲ ਕਿਹੜੇ ਸੰਦ ਹਨ?",
  "Do you work alone or with a team?": "ਕੀ ਤੁਸੀਂ ਇਕੱਲੇ ਜਾਂ ਟੀਮ ਨਾਲ ਕੰਮ ਕਰਦੇ ਹੋ?",
  "How often do you reach job location on time?": "ਤੁਸੀਂ ਕਿੰਨੀ ਵਾਰ ਕੰਮ ਵਾਲੀ ਥਾਂ 'ਤੇ ਸਮੇਂ ਸਿਰ ਪਹੁੰਚਦੇ ਹੋ?",
  "Are you willing to accept auto-assigned jobs from WorkLink?": "ਕੀ ਤੁਸੀਂ WorkLink ਤੋਂ ਸਵੈ-ਸਪੁਰਦ ਨੌਕਰੀਆਂ ਨੂੰ ਸਵੀਕਾਰ ਕਰਨ ਲਈ ਤਿਆਰ ਹੋ?",
  "Are you okay with platform commission on each job?": "ਕੀ ਤੁਸੀਂ ਹਰੇਕ ਕੰਮ 'ਤੇ ਪਲੇਟਫਾਰਮ ਕਮਿਸ਼ਨ ਨਾਲ ਠੀਕ ਹੋ?",
  "Will you follow WorkLink service standards and behavior rules?": "ਕੀ ਤੁਸੀਂ WorkLink ਸੇਵਾ ਦੇ ਮਿਆਰਾਂ ਅਤੇ ਵਿਹਾਰ ਨਿਯਮਾਂ ਦੀ ਪਾਲਣਾ ਕਰੋਗੇ?",
  "Are you ready for full verification (ID & background check)?": "ਕੀ ਤੁਸੀਂ ਪੂਰੀ ਤਸਦੀਕ (ਆਈ.ਡੀ. ਅਤੇ ਪਿਛੋਕੜ ਦੀ ਜਾਂਚ) ਲਈ ਤਿਆਰ ਹੋ?",
  "Are you ready for offline skill testing?": "ਕੀ ਤੁਸੀਂ ਔਫਲਾਈਨ ਹੁਨਰ ਟੈਸਟਿੰਗ ਲਈ ਤਿਆਰ ਹੋ?",
  "Are you open to training before activation (if required)?": "ਕੀ ਤੁਸੀਂ ਸਰਗਰਮੀ ਤੋਂ ਪਹਿਲਾਂ ਸਿਖਲਾਈ ਲਈ ਖੁੱਲ੍ਹੇ ਹੋ (ਜੇ ਲੋੜ ਹੋਵੇ)?",
  "How will you work with WorkLink?": "ਤੁਸੀਂ WorkLink ਨਾਲ ਕਿਵੇਂ ਕੰਮ ਕਰੋਗੇ?",
  "How many hours can you work daily?": "ਤੁਸੀਂ ਰੋਜ਼ਾਨਾ ਕਿੰਨੇ ਘੰਟੇ ਕੰਮ ਕਰ ਸਕਦੇ ਹੋ?",
  "Upload photos of your past work (required)": "ਆਪਣੇ ਪਿਛਲੇ ਕੰਮ ਦੀਆਂ ਫੋਟੋਆਂ ਅੱਪਲੋਡ ਕਰੋ (ਲੋੜੀਂਦਾ)",
  "Can you provide a previous client reference?": "ਕੀ ਤੁਸੀਂ ਪਿਛਲੇ ਗਾਹਕ ਦਾ ਹਵਾਲਾ ਪ੍ਰਦਾਨ ਕਰ ਸਕਦੇ ਹੋ?",
  "Submit Application": "ਅਰਜ਼ੀ ਜਮ੍ਹਾਂ ਕਰੋ",
  "Priority Matches": "ਤਰਜੀਹੀ ਮੈਚ",
  "Workforce Development": "ਕਾਰਜਬਲ ਵਿਕਾਸ",
  "Looking for matches...": "ਮੈਚ ਲੱਭ ਰਿਹਾ ਹੈ...",
  "Priority assignments will appear here": "ਤਰਜੀਹੀ ਕਾਰਜ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ",
};

const translationsFile = 'd:\\Worklink (botted)\\lib\\translations.ts';
let code = fs.readFileSync(translationsFile, 'utf8');

// Find hi object end
let hiInsertPoint = code.indexOf('pa: {') - 5;
if(hiInsertPoint < 0) hiInsertPoint = code.indexOf('pa: {') - 2;

let hiStrings = '';
for (let key in surveyTranslationsHi) {
  hiStrings += `    '${key.replace(/'/g, "\\'")}': '${surveyTranslationsHi[key].replace(/'/g, "\\'")}',\n`;
}

// Find pa object end
let paInsertPoint = code.lastIndexOf('}');
let paStrings = '';
for (let key in surveyTranslationsPa) {
  paStrings += `    '${key.replace(/'/g, "\\'")}': '${surveyTranslationsPa[key].replace(/'/g, "\\'")}',\n`;
}

// Update the code using replace to insert correctly
// Better: Regex replacement
const regexHi = /(hi: \{[\s\S]*?)(  \},)/;
const regexPa = /(pa: \{[\s\S]*?)(\n  \}\n\};?)/;

code = code.replace(regexHi, `$1${hiStrings}$2`);
code = code.replace(regexPa, `$1${paStrings}$2`);

fs.writeFileSync(translationsFile, code);
console.log('Translations merged!');
